---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: swaygo
# description will be included in the image's metadata
description: Sway on Legion Go(wip)

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/sway
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:

  - type: containerfile
    snippets:
      - COPY --from=ghcr.io/ublue-os/bazzite-kernel:41 /tmp/rpms /tmp/rpms/kernel
  - type: script
    scripts:
      - installkernel.sh
      # - xpad.sh
      # - ublue-acpi_call.sh

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/hhd-dev/hhd/repo/fedora-%OS_VERSION%/hhd-dev-hhd-fedora-%OS_VERSION%.repo
    install:
      - hhd
      - hhd-ui
      - adjustor
      - git-crypt
      - subversion
      - tailscale
      - wdisplays
      - ydotool
      - qt6-qtvirtualkeyboard
      - acpica-tools
      - input-remapper
      - pipewire-alsa
      - pipewire-gstreamer
      - pipewire-jack-audio-connection-kit
      - pipewire-jack-audio-connection-kit-libs
      - pipewire-libs
      - pipewire-pulseaudio
      - pipewire-utils
      - pipewire-plugin-libcamera
    remove:
      - firefox
      - firefox-langpacks
      - tuned
      - tuned-ppd

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - NerdFontsSymbolsOnly

  - type: default-flatpaks
    notify: true
    system:
      install:
        - com.vivaldi.Vivaldi
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
    user: {}

  - type: containerfile
    snippets:
      - sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/rpmfusion-*.repo

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
