---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: swaygo
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/sway
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    install:
      - tailscale
      - subversion
      - neovim
    remove:
      - firefox
      - firefox-langpacks

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans

  - type: default-flatpaks
    notify: true
    system:
      install:
        - com.vivaldi.Vivaldi
        - org.telegram.desktop
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
    user: {}

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
